[package]
name = "beyond_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.8.7"
glium = "0.34.0"
hecs = "0.10.4"
image = "0.24.8"
nalgebra = "0.32.3"
rustc-hash = "1.1.0"
thiserror = "1.0.56"
winit = "0.29.10"
